# Store all sensitive API keys and credentials here
# DO NOT commit this file to version control

[github]
token = ""

[groq]
token = ""

[openrouter]
token = ""

[a4f]
token = ""

[weather]
token = ""

[email]
sender = ""
password = ""

[websearch]
token = ""
