# Store all sensitive API keys and credentials here
# DO NOT commit this file to version control

[github]
token = "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"

[groq]
token = "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"

[openrouter]
token = "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"

[a4f]
token = "ddc-a4f-21aeaeaebe4a41808a3c01cd4fe16b2f"

[weather]
token = "6fa922409f28bebc0991def75a5accab"

[email]
sender = "betoni2316@gmail.com"
password = "uijt hcce qprb frcr"

[websearch]
token = "be079c48e1e1df5928813172860bc4d5e73b6a16"
