# Store all sensitive API keys and credentials here
# DO NOT commit this file to version control

[openrouter]
token = "your_openrouter_token"

[github]
token = "your_github_api_token"

[groq]
token = "your_groq_api_key"

[a4f]
token = "your_a4f_api_key"

[weather]
token = "your_openweathermap_api_key"

[email]
sender = "your_email@gmail.com"
password = "your_email_password"
